package net.unethicalite.api.game;

import com.google.common.collect.ImmutableSet;
import java.util.Set;
import net.runelite.api.AnimationID;

public class Animations {
	public static final Set<Integer> FISHING_ANIMATIONS = ImmutableSet.of(
			AnimationID.HUMAN_HARPOON_BARBED,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_BLANK,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_SHARK_2,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_SHARK_1,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_1,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_2,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_TUNA_1,
			AnimationID.BRUT_PLAYER_HAND_FISHING_END_TUNA_2,
			AnimationID.BRUT_PLAYER_HAND_FISHING_START,
			AnimationID.BRUT_PLAYER_HAND_FISHING_READY,
			AnimationID.HUMAN_LARGENET,
			AnimationID.HUMAN_LOBSTER,
			AnimationID.HUMAN_HARPOON_CRYSTAL,
			AnimationID.HUMAN_HARPOON_DRAGON,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_NO_INFERNAL,
			AnimationID.HUMAN_HARPOON,
			AnimationID.HUMAN_HARPOON_INFERNAL,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED,
			AnimationID.HUMAN_HARPOON_LEAGUE_TRAILBLAZER,
			AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED_NO_INFERNAL,
			AnimationID.HUMAN_OCTOPUS_POT,
			AnimationID.HUMAN_SMALLNET,
			AnimationID.HUMAN_FISHING_CASTING,
			AnimationID.HUMAN_FISH_ONSPOT,
			AnimationID.HUMAN_FISHING_CASTING_PEARL,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_FLY,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_BRUT,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL_FLY,
			AnimationID.HUMAN_FISH_ONSPOT_PEARL_BRUT,
			AnimationID.HUMAN_FISHING_CASTING_PEARL_OILY,
			AnimationID.HUMAN_FISHING_ONSPOT_BRUT);

	public static final Set<Integer> MINING_ANIMATIONS = ImmutableSet.of(
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_BRONZE,

			AnimationID.HUMAN_MINING_IRON_PICKAXE,
			AnimationID.HUMAN_MINING_IRON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_IRON_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_IRON,

			AnimationID.HUMAN_MINING_STEEL_PICKAXE,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_STEEL,

			AnimationID.HUMAN_MINING_BLACK_PICKAXE,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_BLACK,

			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_MITHRIL,

			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_ADAMANT,

			AnimationID.HUMAN_MINING_RUNE_PICKAXE,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_RUNE,

			AnimationID.HUMAN_MINING_GILDED_PICKAXE,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_GILDED,

			AnimationID.HUMAN_MINING_DRAGON_PICKAXE,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_DRAGON,

			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_ZALCANO,

			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_TRAILBLAZER_NO_INFERNAL,

			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_NOREACHFORWARD,

			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_PRETTY,

			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_INFERNAL,

			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_TRAILBLAZER,

			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NOREACHFORWARD,

			AnimationID.HUMAN_MINING_3A_PICKAXE,
			AnimationID.HUMAN_MINING_3A_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_3A_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_3A,

			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_CRYSTAL,

			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_NOREACHFORWARD,
			AnimationID.PICKAXE_POWER_SWING_LEAGUE_TRAILBLAZER);

	public static final Set<Integer> WAll_ANIMATIONS = ImmutableSet.of(
			AnimationID.HUMAN_MINING_3A_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BLACK_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_BRONZE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL,
			AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL,
			AnimationID.HUMAN_MINING_GILDED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_IRON_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_RUNE_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_STEEL_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL,
			AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL);
}
